FROM node:20-slim AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .


RUN npm run build 

FROM node:20-slim

WORKDIR /app
COPY package.json ./

RUN npm install -g serve 

COPY --from=builder /app/dist /app/dist 

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]